'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { flushSync } from 'react-dom';
import { BatteryCharging, ArrowRight, ArrowLeft, Network, BookOpen, Factory, Zap, Hospital, Server, RadioTower, Sun, UtilityPole, Landmark, ShieldCheck, CircleHelp, ExternalLink, Pause, Play, Check, BriefcaseBusiness, Layers, GraduationCap, ChevronRight } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from '@/components/ui/tooltip';
import { SidebarProvider, Sidebar, SidebarContent, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import d from '@/data/learning.json';
import EssSimulator from '@/components/ess-simulator';
import WorkExperience from '@/components/work-experience';
const modes=['会社全体','社会インフラ','ESS','営業企画','面接対策'];
const modeChapters=[[0,1,2,3,4,5,6],[1,2,3,4],[2,3,4],[4,5,6],[6,5,4,2]];
const icons=[Hospital,Factory,Server,RadioTower,Sun,UtilityPole,Landmark,ShieldCheck];
type Detail={title:string;body:string;source?:string;label?:string};
function Source({id}:{id:string}){const s=d.sources.find(s=>s.id===id);return s?<a className="source" href={s.url} target="_blank" rel="noreferrer">出典：{s.title}<ExternalLink size={12}/></a>:null}
function Badge({children='学習用の整理'}:{children?:ReactNode}){return <span className={'badge '+(String(children).includes('公式')?'official':'')}>{children}</span>}
function Panel({title,tag,children}:{title:string;tag?:string;children:ReactNode}){return <section className="panel"><div className="paneltitle"><h2>{title}</h2>{tag&&<Badge>{tag}</Badge>}</div>{children}</section>}
function Navigation({chapter,go,mode}:{chapter:number;go:(n:number)=>void;mode:number}){const {setOpenMobile}=useSidebar();return <Sidebar className="navside"><SidebarContent><div className="navintro">LEARNING PATH<span>全体から、仕事へ。</span></div><SidebarMenu>{d.chapters.map((c,i)=><SidebarMenuItem key={c.title}><SidebarMenuButton className={'chapterbtn '+(!modeChapters[mode].includes(i)?'dim':'')} isActive={i===chapter} onClick={()=>{go(i);setOpenMobile(false)}}><span className="chapterNo">0{i+1}</span><span>{c.title}</span>{i===chapter&&<ChevronRight size={16}/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="navfoot"><BookOpen size={22}/><strong>知識を、自分の言葉へ</strong><span>図を見る → 深掘りする →<br/>問いに答える</span><small>確認日 {d.updated}<br/>個人学習用・非公式</small></div></SidebarContent></Sidebar>}
export default function Home(){const [chapter,setChapter]=useState(0),[mode,setMode]=useState(0),[detail,setDetail]=useState<Detail|null>(null),[dictionary,setDictionary]=useState(false),[sources,setSources]=useState(false),[answer,setAnswer]=useState(false),[scenario,setScenario]=useState('charge'),[paused,setPaused]=useState(false),[useCase,setUseCase]=useState(0),[after,setAfter]=useState(true),[flowStep,setFlowStep]=useState(0),[caseItem,setCaseItem]=useState(0),[proposal,setProposal]=useState(false),[experience,setExperience]=useState(0);
 const go=(n:number)=>{setChapter(n);setAnswer(false);setFlowStep(0);window.scrollTo({top:0,behavior:'smooth'})};
 const explain=(title:string,body:string,source?:string,label='学習用の整理')=>setDetail({title,body,source,label});
 useEffect(()=>{type Ctx={registerTool:(t:{name:string;description:string;inputSchema:object;annotations:object;execute:(x:unknown)=>unknown},o:{signal:AbortSignal})=>unknown};const context=(document as Document &{modelContext?:Ctx}).modelContext;if(!context?.registerTool)return;const ac=new AbortController();try{Promise.resolve(context.registerTool({name:'configure_ess_learning',description:'学習章と充放電シナリオを切り替える。',inputSchema:{type:'object',properties:{chapter:{type:'integer',minimum:1,maximum:7},scenario:{type:'string',enum:['charge','discharge']}},required:['chapter'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const x=input as {chapter:number;scenario?:string};if(!x||!Number.isInteger(x.chapter)||x.chapter<1||x.chapter>7||(x.scenario!==undefined&&!['charge','discharge'].includes(x.scenario)))throw Error('chapter must be 1–7; scenario must be charge or discharge');flushSync(()=>{setChapter(x.chapter-1);setAnswer(false);if(x.scenario)setScenario(x.scenario)});return {chapter:x.chapter,scenario:x.scenario??'unchanged'};}},{signal:ac.signal})).catch(()=>{});}catch{}return ()=>ac.abort()},[]);
 useEffect(()=>{if(window.location.hash==='#ess'){setMode(2);setChapter(2)}else if(window.location.hash==='#work'){setMode(3);setChapter(5)}},[]);
 const c=d.chapters[chapter],u=d.uses[useCase];
 const flow=(items:string[][],source?:string)=> <div className="flow">{items.map(([name,body],i)=><div className="flowunit" key={name}><button onClick={()=>explain(name,body,source)}><span>{String(i+1).padStart(2,'0')}</span>{name}</button>{i<items.length-1&&<ArrowRight size={16}/>}</div>)}</div>;
 return <TooltipProvider><div className="learning"><header><div className="brand"><BatteryCharging/> akipiyopiyo24 <span>PERSONAL LEARNING</span></div><div className="headeractions"><a className="primary" href="/akipiyopiyo24/game/">ESS経営ゲーム</a><button onClick={()=>setDictionary(true)}><BookOpen size={17}/>用語辞典</button><button onClick={()=>setSources(true)}><ExternalLink size={16}/>出典</button></div></header><div className="topline"><span>LEARNING MODE</span><Tabs value={String(mode)} onValueChange={v=>{const m=Number(v);setMode(m);go(modeChapters[m][0])}}><TabsList>{modes.map((m,i)=><TabsTrigger key={m} value={String(i)}>{m}</TabsTrigger>)}</TabsList></Tabs></div><SidebarProvider className="shell"><Navigation chapter={chapter} mode={mode} go={go}/><main className="workspace"><div className="mobileNav"><SidebarTrigger/>学習チャプター</div><section className="pagehead"><span className="eyebrow">CHAPTER 0{chapter+1} / 07　 ·　{modes[mode]}モード</span><h1>{c.heading}</h1><p>{c.sub}</p></section>
 {chapter===0&&<><div className="sim-entry"><div><strong>ESSの現場と仕事を見学する</strong><span>相談 → 導入 → 運転 → 異常対応 → 事業改善</span></div><button className="primary" onClick={()=>{setMode(3);go(5)}}><Play size={16}/>仕事体験へ</button></div><div className="sim-entry"><div><strong>ESSを動かして、仕組みをつかむ</strong><span>発電・需要・容量を変えて、24時間をシミュレーション。</span></div><button className="primary" onClick={()=>{setMode(2);go(2)}}><Play size={16}/>シミュレーションへ</button></div><Panel title="2つの領域から見る事業マップ" tag="公式資料をもとに構成"><div className="map"><div className="mapcenter"><BatteryCharging size={36}/><strong>GSユアサ</strong><span>電池と電源システム</span></div><div className="branches"><button className="node" onClick={()=>explain('Mobility：移動を支える','自動車・二輪車・車載用電池など。既存事業の収益力を高め、成長投資の原資を生み出すという戦略。','plan','公式情報の要約')}><Factory/><strong>Mobility</strong><span>自動車・二輪車・車載用電池</span></button><button className="node focus" onClick={()=>go(1)}><Zap/><strong>Social Infrastructure</strong><span>非常用電源・ESS・産業用途</span><b>社会インフラへ深掘り <ArrowRight size={16}/></b></button></div></div><p className="fine">戦略領域で整理した学習用マップです。会計上のセグメントや正式な組織図とは異なります。</p><Source id="plan"/></Panel><Panel title="どんな顧客に、何を届ける？"><div className="businessgrid">{['Mobility','Social Infrastructure'].map(g=><div key={g}><h3>{g}</h3><div className="tree">{d.businesses.filter(b=>b.group===g).map(b=><button key={b.name} className={b.name==='ESS'?'selected':''} onClick={()=>explain(b.name,`顧客：${b.customers}\n製品：${b.products}\n市場：${b.market}\n社会課題：${b.problem}\n提供価値：${b.value}`,b.source)}>{b.name}<ChevronRight size={16}/></button>)}</div></div>)}</div><div className="takeaway"><BookOpen/>ESSは、社会インフラを「日常的な充放電」で支える常用分野。</div></Panel></>}
 {chapter===1&&<><Panel title="地域のどこに、蓄電池と電源がある？" tag="代表用途の模式図"><div className="citymap"><div className="citycore"><UtilityPole/><strong>電力インフラ</strong><span>施設を選ぶと用途がわかる</span></div><div className="facilitygrid">{d.facilities.map(([name,,product,body],i)=>{const Icon=icons[i];return <button key={name} className="facility" onClick={()=>explain(name,`${product}\n${body}`,'industrial','代表用途・実際の納入先を示すものではありません')}><Icon size={30}/><strong>{name}</strong><span>{product}</span></button>})}</div></div></Panel><div className="two"><Panel title="非常用：もしもの時をつなぐ"><p>普段は備え、停電等で重要設備を支える。</p><div className="miniFlow">停電 <ArrowRight/> 蓄電池 <ArrowRight/> 重要負荷</div></Panel><Panel title="常用：毎日の電力を調整する"><p>発電と消費の時間差を、充放電で埋める。</p><button className="primary" onClick={()=>go(2)}>ESSの仕組みを見る<ArrowRight size={16}/></button></Panel></div><Source id="industrial"/></>}
 {chapter===2&&<><EssSimulator/><Panel title="充電と放電を切り替える" tag="学習用の概念モデル"><div className="controls"><Tabs value={scenario} onValueChange={v=>setScenario(String(v))}><TabsList><TabsTrigger value="charge">A　電力余剰 → 充電</TabsTrigger><TabsTrigger value="discharge">B　電力不足 → 放電</TabsTrigger></TabsList></Tabs><button className="secondary" onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?'再生':'一時停止'}</button></div><div className={'energy '+scenario+(paused?' paused':'')}><div className="energystate"><span className="liveDot"/>{scenario==='charge'?'再エネの発電量が、需要を上回る':'需要に対して、発電量が足りない'}<b>{scenario==='charge'?'余剰を蓄える':'蓄えた電気を使う'}</b></div><div className="powerdiagram"><div className="energybox"><Sun size={34}/><strong>太陽光・風力</strong><span>{scenario==='charge'?'発電量が多い':'発電量が少ない'}</span></div><div className={'wire '+(scenario==='charge'?'active':'')}><i/><i/><i/><span>→</span></div><div className="energybox"><UtilityPole size={34}/><strong>交流の電力網</strong><span>系統・工場・建物</span></div><div className="wire active reversible"><i/><i/><i/><span>{scenario==='charge'?'→':'←'}</span></div><button className="energybox" onClick={()=>explain('PCS',d.parts[2][1])}><Zap size={34}/><strong>PCS</strong><span>交流 ↔ 直流</span></button><div className="wire active reversible"><i/><i/><i/><span>{scenario==='charge'?'→':'←'}</span></div><button className="energybox battery" onClick={()=>explain('Battery',d.parts[0][1])}><BatteryCharging size={34}/><strong>蓄電池</strong><div className="batterybar"><i/></div><span>{scenario==='charge'?'充電中 → 残量増加':'放電中 → 残量減少'}</span></button></div><div className="controlband"><button onClick={()=>explain('EMS',d.parts[3][1])}>EMS：全体の運転を計画・制御</button><span>···· 制御・情報のつながり ····</span><button onClick={()=>explain('BMS',d.parts[1][1])}>BMS：電池を管理・保護</button></div></div><p className="fine">交流側に接続する構成例。配線・変圧器等を簡略化しています。粒子と残量は方向を学ぶ繰り返し表現で、実測値ではありません。</p><div className="partgrid">{d.parts.map(([name,body])=><Tooltip key={name}><TooltipTrigger className="part" onClick={()=>explain(name,body)}>{name}<CircleHelp size={14}/></TooltipTrigger><TooltipContent className="termtooltip">{body}</TooltipContent></Tooltip>)}</div></Panel><div className="two"><Panel title="kW = どれだけ一度に出せるか"><div className="bigNumber">25 <small>MW</small></div><p>出力。電気を出し入れする速さに相当。</p></Panel><Panel title="kWh = どれだけ蓄えられるか"><div className="bigNumber">100 <small>MWh</small></div><p>容量。100MWh ÷ 25MW = 理想上4時間。<br/>実際は損失や使える容量の範囲で短くなります。</p></Panel></div><p className="fine">上の数値は単位理解のための仮定。GSユアサの特定製品仕様ではありません。</p><Source id="products"/></>}
 {chapter===3&&<><Panel title="ESSの3つの使い方"><Tabs value={String(useCase)} onValueChange={v=>setUseCase(Number(v))}><TabsList className="useTabs">{d.uses.map((v,i)=><TabsTrigger key={v.name} value={String(i)}>{v.name}</TabsTrigger>)}</TabsList></Tabs><div className="useflow">{u.flow.map((v,i)=><div className="useunit" key={i}><div><span>0{i+1}</span><strong>{v}</strong></div>{i<2&&<span className="doublearrow">↔</span>}</div>)}</div><div className="two"><div><span className="eyebrow">社会・顧客の課題</span><h3>{u.problem}</h3></div><div><span className="eyebrow">ESSの役割</span><h3>{u.solution}</h3></div></div><div className="chips">{u.value.map(v=><span key={v}>{v}</span>)}</div><div className="compare"><div className="controls"><h3>導入前後を比べる</h3><Tabs value={after?'after':'before'} onValueChange={v=>setAfter(v==='after')}><TabsList><TabsTrigger value="before">Before</TabsTrigger><TabsTrigger value="after">After</TabsTrigger></TabsList></Tabs></div><div className={'comparison '+(after?'improved':'')} key={String(after)+useCase}><strong>{after?'ESS導入後':'ESS導入前'}</strong><p>{after?u.after:u.before}</p></div></div></Panel>{useCase===1&&<Panel title="3つの市場では、取引する価値が違う" tag="制度の概要"><div className="three"><div><h3>卸電力市場</h3><p>電気そのもの（kWh）。買う時間と売る時間の価格差など。</p></div><div><h3>需給調整市場</h3><p>調整できる力（ΔkW）と、指令に応じた調整電力量。</p><Source id="eprx"/></div><div><h3>容量市場</h3><p>将来の供給力（kW）を確保する仕組み。</p><Source id="capacity"/></div></div><p className="fine">参加・性能要件や同時供出の制約があります。収益の単純な足し算はできません。</p></Panel>}<Panel title="社会への影響をたどる" tag="効果は設計・運用条件による"><div className="impactmap"><div className="impactcenter"><BatteryCharging/><strong>ESS</strong></div><div className="impactnodes">{d.impacts.map(([name,body])=><button key={name} onClick={()=>explain(name,body)}><span className="impactline"/>{name}<ChevronRight size={14}/></button>)}</div></div></Panel></>}
 {chapter===4&&<><Panel title="価値が生まれるプロセス" tag="公式製品情報をもとに学習用に整理">{flow(d.valueFlow,'products')}<p className="fine">一社がすべての工程を単独で担うとは限りません。施工・制御・運用等の役割は契約と連携体制で変わります。</p><Source id="products"/></Panel><div className="two"><Panel title="モノ：動かすための設備"><div className="chips">{['電池','PCS','制御機器','電源設備'].map(x=><span key={x}>{x}</span>)}</div><p>機器とシステムを届ける。</p></Panel><Panel title="コト：使い続けられる状態"><div className="chips">{['安定稼働','遠隔監視','メンテナンス','予防保全','長期運用','エネルギーマネジメント'].map(x=><span key={x}>{x}</span>)}</div><p>導入後の価値を支える。</p></Panel></div><div className="valuebanner"><span>電池を売る</span><ArrowRight/><strong>エネルギーを安定して使える状態を提供する</strong></div><Panel title="STARELINK：導入後も、設備を見守る" tag="公式情報の要約">{flow([['導入','対象機器・契約サービスを確認。'],['遠隔監視','離れた場所から設備の状態を把握。'],['データ収集','運転情報を蓄積する。'],['状態診断','状態を分析し、変化を把握する。'],['異常検知','異常や予兆の把握を保守対応につなぐ。'],['保守','必要な点検や対応を行う。'],['長期安定稼働','安心・安全な運用を支える。']],'service')}<p className="fine">サービスの対象、保証、対応範囲はメニュー・契約条件によって異なります。</p><Source id="service"/></Panel><Panel title="ESS・AIDCの事業フェーズ" tag="2026年5月の会社計画"><div className="timeline"><div><span>第六次中計</span><strong>市場立ち上がり</strong><p>再エネ・AIデータセンターの需要拡大</p></div><div className="now"><Badge>現在：2026年度</Badge><strong>事業構築・先行投資</strong><p>第七次中計。ESS工場投資、2028年度下期の稼働を計画。</p></div><div><span>2029年度〜 第八次中計以降</span><strong>投資回収・飛躍</strong><p>新工場・新製品を軸に国内外の販売とサービスを拡大する計画。</p></div></div><p className="fine">将来は会社の計画であり、達成済みの実績ではありません。ESSとAIDCを合わせた領域の説明です。</p><Source id="phase"/></Panel><Panel title="顧客の収益と、GSユアサの収益を分ける" tag="事業構造の整理"><div className="two"><div><h3>設備・サービスを提供する側</h3><p>機器・システムの販売、保守等の契約で対価を得る。費用・品質・納期・長期対応が採算に影響。</p></div><div><h3>蓄電所を保有・運用する側</h3><p>市場取引等で運用価値を得る。充電費、劣化、損失、運転・保守費を負担。</p></div></div><div className="takeaway">GSユアサを選ぶ理由の検討軸：電池と電源の技術、システム実績、運用支援。競合優位を断定するには、他社の同条件比較が必要。</div></Panel></>}
 {chapter===5&&<><WorkExperience/><Panel title="営業企画は、誰とつながる？" tag="求人からの推論・関係者の想定"><div className="jobmap"><div className="jobcenter"><BriefcaseBusiness size={32}/><strong>営業企画</strong><span>市場 → 判断 → 実行</span></div><div className="stakeholders">{d.stakeholders.map(([name,body])=><button key={name} onClick={()=>explain(name,body,'job','求人からの推論')}>{name}<ChevronRight size={14}/></button>)}</div></div></Panel><Panel title="情報を、事業の成果へ変える" tag="工程と具体例は学習用の想定"><div className="inputs">{['市場情報','顧客情報','競合情報','政策・制度'].map(x=><span key={x}>{x}</span>)}<span>↓</span></div><div className="jobsteps">{d.jobFlow.map(([name],i)=><button key={name} className={i===flowStep?'active':''} onClick={()=>setFlowStep(i)}><small>0{i+1}</small>{name}</button>)}</div><div className="stepdetail" key={flowStep}><span className="eyebrow">STEP 0{flowStep+1}</span><h3>{d.jobFlow[flowStep][0]}</h3><p>{d.jobFlow[flowStep][1]}</p><button className="secondary" onClick={()=>setFlowStep((flowStep+1)%d.jobFlow.length)}>次の工程 <ArrowRight size={16}/></button></div><div className="outputs">売上・利益・顧客価値へつなぐ</div></Panel><Panel title="公式求人と、そこから考えられる仕事"><div className="two"><div><Badge>公式求人に記載</Badge><ul><li>国内外の定置用蓄電事業の企画・実行</li><li>市場・顧客・競合の調査、販売促進、製品企画</li><li>社外連携体制の構築、渉外活動</li></ul><Source id="job"/></div><div><Badge>求人からの推論</Badge><ul><li>事業計画・収益や採算の検討</li><li>開発・生産・サービスとの実現性の調整</li><li>計画と実績の差を分析して改善</li></ul><p className="fine">担当範囲・意思決定権限・分業は面接で確認。</p></div></div></Panel><Panel title="1案件を追う：100MWh級ESSの導入相談" tag="仮想案件・実案件ではありません"><p>再エネ事業者から相談。まず何を確認し、どう企画する？</p><div className="casegrid"><div className="caseoptions">{d.caseInfo.map(([name],i)=><button key={name} className={i===caseItem?'selected':''} onClick={()=>setCaseItem(i)}>{name}</button>)}</div><div className="caseinfo"><span className="eyebrow">INFORMATION 0{caseItem+1}</span><h3>{d.caseInfo[caseItem][0]}</h3><p>{d.caseInfo[caseItem][1]}</p></div></div><button className="primary" onClick={()=>setProposal(!proposal)}>{proposal?'提案例を閉じる':'情報をまとめた提案例を見る'}<ArrowRight size={16}/></button>{proposal&&<div className="stepdetail"><h3>段階的に条件を固める企画</h3><ol><li>余剰吸収・収益化の優先度と、必要出力・容量を合意する。</li><li>系統接続、供給能力、費用、納期の成立条件を確認する。</li><li>価格変動・劣化・費用増を含む複数シナリオで採算を検討する。</li><li>保守・保証・外部運用者の役割を含めた提案を営業と組み立てる。</li></ol><p>結論：100MWhという容量だけで価格や採算を決めず、運用目的と実現条件から企画する。</p></div>}</Panel></>}
 {chapter===6&&<><Panel title="経験を、仕事につなげる" tag="要件定義書の経験例・本人の実績確認は未実施"><Tabs value={String(experience)} onValueChange={v=>setExperience(Number(v))}><TabsList>{d.experiences.map(([name],i)=><TabsTrigger key={name} value={String(i)}>{name}</TabsTrigger>)}</TabsList></Tabs><div className="experience"><div><span className="eyebrow">これまでの経験例</span><h3>{d.experiences[experience][0]}</h3><p>{d.experiences[experience][1]}</p></div><ArrowRight/><div><span className="eyebrow">ESS営業企画での接点</span><h3>{d.experiences[experience][2]}</h3><p>どんな課題を、誰と、どう解き、何が変わったかを具体化する。</p></div></div></Panel><Panel title="未経験・キャッチアップが必要な領域"><div className="two">{[['ESS専門知識','電池・PCS・EMS、容量と出力、劣化・安全・保守。'],['電力市場','卸・需給調整・容量市場で、売る価値と参加条件を整理。'],['エネルギー政策','再エネ、系統接続、支援制度、公募要件の読み方。'],['海外ビジネス','語学・交渉・地域ごとの制度と商習慣。']].map(([name,body])=><div className="studycard" key={name}><Badge>要件定義書上の未経験領域</Badge><h3>{name}</h3><p>{body}</p></div>)}</div><div className="takeaway"><CircleHelp/>公式求人は業界動向・電力市場と政策の知識を必須要件に含めています。経験の転用に加え、知識の具体化が必要です。</div><Source id="job"/></Panel><Panel title="面接で、自分の言葉にする"><div className="interviewprompts">{[['志望動機','社会課題への関心 → GSユアサの提供価値 → 営業企画で貢献したいこと。'],['経験の接点','自分の課題解決事例 → 活かせる力 → ESSでの応用。'],['逆質問','企画部門が重視する成果指標は？ 開発・営業との役割分担は？ 今の事業構築で優先する課題は？']].map(([name,body])=><details key={name}><summary>{name}</summary><p>{body}</p></details>)}</div><p className="fine">回答の枠組みです。実体験・実績は自分の事例に置き換えてください。</p></Panel></>}
 <section className="reflection"><div><span className="eyebrow">CHECK YOUR UNDERSTANDING</span><h3>{c.question}</h3></div><button className="secondary" onClick={()=>setAnswer(!answer)}>{answer?'閉じる':'説明のヒント'}</button>{answer&&<p className="answer">{c.answer}</p>}</section><nav className="bottomnav" aria-label="章の移動"><button className="secondary" disabled={chapter===0} onClick={()=>go(chapter-1)}><ArrowLeft size={16}/>前の章</button><span>0{chapter+1} / 07</span><button className="primary" onClick={()=>go(chapter===6?0:chapter+1)}>{chapter===6?'全体像に戻る':'次の章へ'}<ArrowRight size={16}/></button></nav><footer>公式資料と一般的な仕組みをもとに構成した学習用アプリ。企業公式の教材ではありません。<br/>内容確認：{d.updated}　<button onClick={()=>setSources(true)}>出典と情報の区分を見る</button></footer></main></SidebarProvider>
 <Dialog open={!!detail} onOpenChange={o=>{if(!o)setDetail(null)}}><DialogContent className="detaildialog"><DialogTitle>{detail?.title}</DialogTitle><DialogDescription render={<div/>}><Badge>{detail?.label}</Badge><p className="detailbody">{detail?.body}</p>{detail?.source&&<Source id={detail.source}/>}</DialogDescription></DialogContent></Dialog>
 <Dialog open={dictionary} onOpenChange={setDictionary}><DialogContent className="dictionary"><DialogTitle>用語辞典</DialogTitle><DialogDescription>気になる用語を開いて確認できます。</DialogDescription><div className="terms">{d.terms.map(([name,body])=><details key={name}><summary>{name}</summary><p>{body}</p></details>)}</div><div className="fine">制度の詳細は公式資料を確認：<Source id="eprx"/><Source id="capacity"/><Source id="auction"/></div></DialogContent></Dialog>
 <Dialog open={sources} onOpenChange={setSources}><DialogContent className="dictionary"><DialogTitle>出典と情報の区分</DialogTitle><DialogDescription>確認日 {d.updated}。公式の事実、一般的な説明、推論を区別しています。</DialogDescription><div className="sourceguide"><Badge>公式情報の要約</Badge><span>公表資料に基づく内容</span><Badge>学習用の整理</Badge><span>仕組み・用途の説明と模式図</span><Badge>求人からの推論／想定</Badge><span>業務の具体例・関係者・仮想案件</span></div><div className="sourcelist">{d.sources.map(s=><div key={s.id}><Source id={s.id}/><p>{s.note}</p></div>)}</div><p className="fine">Phase 2の競合比較・市場規模・シェア・業績グラフ・市場予測は未収録です。</p></DialogContent></Dialog>
 </div></TooltipProvider>
}




