'use client';
import {useEffect,useMemo,useState,type CSSProperties} from 'react';
import {Sun,Factory,BatteryCharging,UtilityPole,Play,Pause,RotateCcw,ArrowRight} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {DEFAULT,simulate,totals,type Config} from '@/lib/ess-model';
const number=(n:number)=>Math.round(n).toLocaleString('ja-JP');
const clock=(h:number)=>`${String(Math.floor(h)).padStart(2,'0')}:${h%1===0?'00':String(Math.round(h%1*60)).padStart(2,'0')}`;
const presets=[{name:'晴れた1日',values:DEFAULT},{name:'昼に雲が広がる',values:{...DEFAULT,cloudy:true}},{name:'小さな蓄電池',values:{...DEFAULT,capacity:300}},{name:'出力が小さい',values:{...DEFAULT,power:80}}];
function Control({label,value,min=0,max,step=10,unit,onChange}:{label:string;value:number;min?:number;max:number;step?:number;unit:string;onChange:(n:number)=>void}){return <div className="sim-control"><div><span>{label}</span><strong>{number(value)} <small>{unit}</small></strong></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>}
export default function EssSimulator(){
 const [config,setConfig]=useState<Config>(DEFAULT),[index,setIndex]=useState(0),[running,setRunning]=useState(false),[speed,setSpeed]=useState('1'),[preset,setPreset]=useState('0');
 const samples=useMemo(()=>simulate(config),[config]);const s=samples[index],sum=totals(samples.slice(0,index+1));
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>setIndex(i=>{if(i>=95){setRunning(false);return 95}return i+1}),250/Number(speed));return ()=>clearInterval(timer)},[running,speed]);
 const change=(key:keyof Config,value:number)=>{setRunning(false);setIndex(0);setPreset('custom');setConfig(c=>({...c,[key]:value}))};
 const charge=s.charge>0.01,discharge=s.discharge>0.01;
 const status=charge?'余った電気を充電':discharge?'蓄えた電気を放電':s.energyEnd<.01?'電池が空：系統から供給':s.energyEnd>=config.capacity-.01?'満充電：余剰を抑制':'充放電せず待機';
 const pct=config.capacity?s.energyEnd/config.capacity*100:0;
 const maxPower=Math.max(100,...samples.flatMap(v=>[v.solar,v.demand,v.baselineGrid]));
 const x=(i:number)=>50+i/95*800,y=(v:number)=>190-v/maxPower*155;
 const path=(key:'solar'|'demand'|'grid'|'baselineGrid')=>samples.map((v,i)=>`${i?'L':'M'}${x(i)},${y(v[key])}`).join(' ');
 const flowStyle=(power:number)=>({'--travel':`${Math.max(.45,2.6-power/500)}s`} as CSSProperties);
 return <section className="panel simulator" id="ess-simulator"><div className="paneltitle"><h2>ESSの1日を動かしてみる</h2><span className="badge">仮想の需要家・学習用シミュレーション</span></div><p>昼に蓄えた電気は、夕方まで持つ？ 条件を変えて、電気の行き先を確かめましょう。</p><Tabs value={preset} onValueChange={v=>{const p=Number(v);if(!presets[p])return;setPreset(String(v));setConfig({...presets[p].values});setIndex(0);setRunning(false)}}><TabsList className="sim-presets">{presets.map((p,i)=><TabsTrigger key={p.name} value={String(i)}>{p.name}</TabsTrigger>)}</TabsList></Tabs>
 <div className="sim-layout"><div className="sim-settings"><Control label="太陽光の最大出力" value={config.solar} max={1500} step={50} unit="kW" onChange={v=>change('solar',v)}/><Control label="需要の基準値" value={config.demand} min={100} max={1000} step={20} unit="kW" onChange={v=>change('demand',v)}/><Control label="蓄電池の容量" value={config.capacity} min={100} max={4000} step={100} unit="kWh" onChange={v=>change('capacity',v)}/><Control label="充放電の最大出力" value={config.power} min={0} max={1000} step={20} unit="kW" onChange={v=>change('power',v)}/><Control label="開始時の残量" value={config.initialSoc} max={100} step={5} unit="%" onChange={v=>change('initialSoc',v)}/><p className="fine">条件を変えると0時へ戻ります。需要は夕方に増える仮想パターンです。</p></div>
 <div className={'sim-stage '+(running?'is-running':'')}><div className="sim-time"><span>{clock(s.hour)} <small>→ {clock(s.hour+.25)}</small></span><b>{status}</b></div><div className="sim-circuit"><div className="sim-device sim-solar"><Sun size={34}/><strong>太陽光</strong><b>{number(s.solar)} <small>kW</small></b></div><div className={'sim-link '+(s.solar>.01?'flow-on':'')} style={flowStyle(s.solar)}><i/><i/><i/><span>→</span></div><div className="sim-device sim-load"><Factory size={34}/><strong>工場・建物</strong><b>{number(s.demand)} <small>kW</small></b></div><div className={'sim-link '+(s.grid>.01?'flow-on reverse':'')} style={flowStyle(s.grid)}><i/><i/><i/><span>←</span></div><div className="sim-device sim-grid"><UtilityPole size={34}/><strong>系統から購入</strong><b>{number(s.grid)} <small>kW</small></b></div></div><div className="sim-battery-row"><div className={'sim-vertical '+(charge||discharge?'flow-on':'')+(discharge?' reverse':'')} style={flowStyle(s.charge+s.discharge)}><i/><i/><span>{charge?'↓ 充電':discharge?'↑ 放電':'待機'}</span></div><div className="sim-battery"><BatteryCharging size={28}/><div><strong>ESS <span>PCSを含む</span></strong><b>{charge?'+':discharge?'−':''}{number(s.charge+s.discharge)} <small>kW</small></b></div><div className="sim-soc"><div style={{width:`${pct}%`}}/></div><strong>{number(pct)}<small> %</small></strong><span>{number(s.energyEnd)} / {number(config.capacity)} kWh</span></div></div><div className="sim-caption">{charge?'発電で需要を賄い、余剰を電池へ。':discharge?'発電だけで足りない分を電池が補います。':'充放電量が0のため、電池への流れは止まります。'}{s.curtailed>.1&&` 蓄えきれない ${number(s.curtailed)} kW は出力を抑制。`}{s.grid>.1&&` 足りない ${number(s.grid)} kW は系統から供給。`}</div></div></div>
 <div className="sim-playback"><button className="primary" onClick={()=>{if(index>=95)setIndex(0);setRunning(!running)}}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'一時停止':index>=95?'もう一度再生':'1日を再生'}</button><button className="secondary" aria-label="0時にリセット" onClick={()=>{setIndex(0);setRunning(false)}}><RotateCcw size={16}/></button><Tabs value={speed} onValueChange={v=>setSpeed(String(v))}><TabsList><TabsTrigger value="1">標準</TabsTrigger><TabsTrigger value="2">2倍速</TabsTrigger></TabsList></Tabs><span>標準：実時間1秒 ≈ 1時間</span></div><div className="sim-scrub"><label>時刻を動かす：{clock(s.hour)}</label><Slider aria-label="シミュレーション時刻（15分単位）" value={[index]} min={0} max={95} step={1} onValueChange={v=>{setIndex(Array.isArray(v)?v[0]:v);setRunning(false)}}/><div><span>0:00</span><span>6:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></div>
 <div className="sim-chart"><h3>同じ条件で、ESSがない場合と比べる</h3><div className="sim-legend"><span style={{color:'#ce8a08'}}>━ 太陽光</span><span style={{color:'#6f83a1'}}>━ 需要</span><span style={{color:'#ad8491'}}>┄ 購入電力：ESSなし</span><span style={{color:'#176ae5'}}>━ 購入電力：ESSあり</span></div><svg viewBox="0 0 880 228" role="img" aria-label="24時間の発電・需要・ESS導入前後の購入電力。縦軸kW、横軸時刻。時刻スライダーで各時間の数値を確認できます。"><text x="4" y="18">kW</text>{[0,.5,1].map(r=><g key={r}><line x1="50" x2="850" y1={y(r*maxPower)} y2={y(r*maxPower)} stroke="#dce5ef"/><text x="2" y={y(r*maxPower)+4}>{number(r*maxPower)}</text></g>)}<path d={path('baselineGrid')} fill="none" stroke="#ad8491" strokeDasharray="6 5" strokeWidth="2"/><path d={path('solar')} fill="none" stroke="#ce8a08" strokeWidth="2.5"/><path d={path('demand')} fill="none" stroke="#6f83a1" strokeWidth="2"/><path d={path('grid')} fill="none" stroke="#176ae5" strokeWidth="3"/><line x1={x(index)} x2={x(index)} y1="25" y2="195" stroke="#123f76" strokeWidth="2"/><circle cx={x(index)} cy={y(s.grid)} r="5" fill="#176ae5"/>{[0,6,12,18,24].map(h=><text key={h} x={50+h/24*800} y="220" textAnchor="middle">{h}:00</text>)}</svg></div>
 <div className="sim-metrics"><div><span>購入電力量の削減</span><strong>{number(sum.baselineGrid-sum.grid)} <small>kWh</small></strong><p>なし {number(sum.baselineGrid)} → あり {number(sum.grid)}</p></div><div><span>出力抑制の減少</span><strong>{number(sum.baselineCurtailed-sum.curtailed)} <small>kWh</small></strong><p>なし {number(sum.baselineCurtailed)} → あり {number(sum.curtailed)}</p></div><div><span>充放電による損失</span><strong>{number(sum.loss)} <small>kWh</small></strong><p>開始から {clock(s.hour+.25)} までの累計</p></div></div><div className="takeaway"><ArrowRight size={20}/>{s.charge>=config.power-.01&&charge?'充電出力が上限に達しています。容量を増やすだけでは、充電の速さは上がりません。':s.energyEnd>=config.capacity-.01?'電池が満杯です。容量を増やすと、余剰をより多く受け止められる可能性があります。':s.energyEnd<.01?'電池が空になりました。夜間の需要を賄うには、昼の充電量と容量の両方が関係します。':'試してみよう：容量だけを増やす場合と、最大出力だけを増やす場合で、何が変わる？'}</div>
 <details className="sim-assumptions"><summary>計算の前提を見る</summary><p>15分刻みの電力量収支を計算。太陽光は需要に優先供給し、余剰のみで充電します。不足時に放電し、残りは系統から購入します。逆潮流（売電）は行わず、蓄えきれない発電は抑制する仮定です。</p><p>充電・放電効率はそれぞれ95%（往復約90%）という仮定。容量は利用可能容量とし、その0～100%で計算します。温度・劣化・空調・詳細な系統制約・料金・市場取引はモデル化していません。GSユアサ製品の性能や実際の施設を再現するものではありません。</p><p>開始時の電池には過去に充電したエネルギーが入っています。購入電力量の削減にはその放電も含みます。料金削減や経済性を示す数値ではありません。表示は各15分の平均電力と区間終了時の残量です。</p></details></section>
}
