import {useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {SEGMENTS,planningOf,planningCosts,segmentOf,type Game,type Action,type PlanningAction} from '@/lib/ess-game';
export default function SalesPlanning({g,act}:{g:Game;act:(a:Action)=>void}){
 const p=planningOf(g),[view,setView]=useState('market'),[target,setTarget]=useState('industrial'),[count,setCount]=useState(1);
 const button=(task:PlanningAction['task'],choice:string,label:string,done=false,extra={})=><button disabled={g.ended||!p.moves||done||g.cash<planningCosts(task)} onClick={()=>act({type:'planning',task,choice,...extra})}>{done?'✓ 完了':`${label} · ${planningCosts(task)}万円`}</button>;
 const segment=SEGMENTS.find(s=>s.id===target)!;
 return <section className="game-management planning"><div className="game-section-heading"><span className="game-eyebrow">SALES PLANNING OFFICE</span><h1>市場を選び、売れる体制をつくる。</h1><p>営業企画枠：今週 {p.moves}/1 回。案件対応の2判断とは別枠です。企画費は現金と今週の費用に反映されます。</p><p>まず市場調査 → 競合比較 → 重点市場・目標設定へ。すべてを一度に行わず、12週で優先順位を決めよう。</p></div>
 <Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList className="planning-tabs">{[['market','市場・計画'],['product','販促・製品'],['partners','社外連携・制度'],['overseas','海外交渉'],['review','実績・改善']].map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList></Tabs>
 {view==='market'&&<><div className="game-team-grid">{SEGMENTS.map(s=><article className="game-card" key={s.id}><h2>{s.name}</h2><p><b>需要：</b>{s.demand}</p><p><b>集める情報：</b>{s.evidence}</p><p><b>論点：</b>{s.risk}</p><p>ゲーム内の候補案件：{s.sites.length}件（実際の市場規模を表す数値ではありません）</p>{button('market',s.id,'市場を調査',p.markets.includes(s.id))}</article>)}</div><article className="game-card"><h2>競合情報を、同じ条件で比較する</h2><p>架空の比較例：A社は「本体価格が低い・施工は別」、B社は「保守を含む・納期が長い」。価格の大小だけでは顧客価値を評価できません。</p><p>必要な出力・容量、施工範囲、保証、保守、納期をそろえ、顧客の優先事項と照合します。調査済み市場が必要です。</p><div className="planning-actions">{button('competition','price-only','本体価格だけで判断',p.competition)}{button('competition','same-scope','提供範囲をそろえて比較',p.competition)}</div></article><article className="game-card"><h2>事業計画を、実行できる目標にする</h2><p>対象市場の調査と競合比較が必要。稼働目標に対して、導入枠・保守枠・資金を確保します。目標の変更も企画枠を使います。</p><label>重点市場 <select value={target} onChange={e=>{setTarget(e.target.value);setCount(1)}}>{SEGMENTS.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label> 稼働目標 <select value={count} onChange={e=>setCount(Number(e.target.value))}>{segment.sites.map((_,i)=><option key={i} value={i+1}>{i+1}件</option>)}</select></label>{button('plan',target,'計画を設定',false,{count})}</article></>}
 {view==='product'&&<><div className="game-team-grid">{SEGMENTS.map(s=><article className="game-card" key={s.id}><h2>{s.name}への販売促進</h2><p>市場調査後、用途別の説明会・提案資料を作成。対象市場の今後の顧客調査費が10→0万円に。顧客調査そのものは1判断必要です。</p><p>競合比較も完了していれば、保守付き提案の10%上乗せ価格を説明できるようになります。実際の受注確率を再現したものではありません。</p>{button('campaign',s.id,'用途別の販促を実施',p.campaigns.includes(s.id))}</article>)}</div><article className="game-card"><h2>顧客の声を製品要求へ</h2><p>市場調査・競合比較後に、開発とサービス部門へ提案する想定。今期は一方のみ選べます。既に契約した案件の原価・仕様は変わりません。</p><p><b>標準化：</b>国内需要家の新規案件原価を8%低減。仕様を満たしたまま設計を共通化。</p><p><b>監視支援：</b>全新規案件の原価が3%増加。稼働後の通常の信頼性低下を毎週2軽減。高温イベントや保守枠不足は引き続き影響します。</p><div className="planning-actions">{button('product','lean','標準化を合意',p.product!=='none')}{button('product','monitor','監視支援を合意',p.product!=='none')}</div><p>選択中：{p.product==='none'?'未決定':p.product==='lean'?'標準化':'監視支援'}</p></article></>}
 {view==='partners'&&<><div className="game-team-grid">{[['epc','施工パートナー','設計・施工の範囲、工程、検収を合意。新規案件の原価＋20万円、工期−1週（最低1週）。社内の導入枠は引き続き必要。'],['operator','運用事業者','系統用案件の受注条件。設備販売・保守と、運用事業者の市場取引収益を区別し、接続・制御・データ連携の責任を整理。'],['overseas','現地パートナー','海外案件の受注条件。施工・保守・問い合わせ窓口を分担し、保証対応の抜けを防ぐ。']].map(([id,title,body])=><article className="game-card" key={id}><h2>{title}</h2><p>{body}</p>{button('partner',id,'役割と条件を合意',p.partners.includes(id))}</article>)}</div><article className="game-card"><h2>制度確認と、根拠に基づく渉外活動</h2><p>市場調査後に、技術・法務等と適用要件を確認。顧客の課題を匿名化し、業界団体への意見や制度改善の提案に整理する想定です。提出を選ぶと制度が都合よく変わる仕組みではありません。</p><ul><li>需要家：接続、保安、自立運転・切替、補助制度の対象条件。</li><li>系統用：系統接続、取引市場ごとの参加要件、計量・制御、運用主体。</li><li>海外：現地認証、輸入条件、電気・安全規則、保証と契約法務。</li></ul><p>以下は確認工程の体験です。実際の法令・市場ルールを網羅する教材ではなく、実案件では対象国・時点の一次資料を確認します。</p><div className="planning-actions">{SEGMENTS.map(s=><span key={s.id}>{button('policy',s.id,s.name+'の確認・意見整理',p.policies.includes(s.id))}</span>)}</div></article></>}
 {view==='overseas'&&<article className="game-card"><h2>海外案件：条件を文書でそろえる</h2><p>市場調査 → 現地企業との連携 → 現地制度確認 → 英文条件の合意。この4工程を終えると、街マップ下部の「海外・現地工場案件」を契約できます。別途、顧客調査・技術Lv.1・適合仕様も必要です。</p><blockquote>“Please confirm the currency, payment schedule, acceptance criteria, warranty coverage and local service responsibilities in writing.”</blockquote><p>通貨・支払日程・受入基準・保証範囲・現地保守の責任分担を文書で確認してください。</p><p>ゲーム上の仮定：国内相当の原価＋8%、工期＋1週、入金は引渡しの2週後。実際の為替相場や国別制度は再現していません。</p><div className="planning-actions">{button('international','price-only','価格だけを合意',p.international)}{button('international','written','条件表と責任分担を合意',p.international)}</div><p>完了状況：市場 {p.markets.includes('overseas')?'✓':'未'} ／ 連携 {p.partners.includes('overseas')?'✓':'未'} ／ 制度 {p.policies.includes('overseas')?'✓':'未'} ／ 英文条件 {p.international?'✓':'未'}</p></article>}
 {view==='review'&&<><article className="game-card"><h2>計画と実績を比較し、次の行動を選ぶ</h2>{p.plan?<p>重点市場：{SEGMENTS.find(s=>s.id===p.plan!.segment)!.name} ／ 稼働実績 {g.projects.filter(s=>s.status==='operating'&&segmentOf(s.id)===p.plan!.segment).length} / 目標 {p.plan.count}件</p>:<p>「市場・計画」で重点市場と稼働目標を設定してください。</p>}<p>現金 {g.cash.toLocaleString()}万円 ／ 累計利益 {g.profit.toLocaleString()}万円 ／ 顧客信頼 {g.trust}/100</p><p>計画設定後、週次決算を1回以上終えると改善案を記録できます。記録だけで成果は増えません。次の週の増員・連携・販促・製品企画へつなげます。</p><div className="planning-actions">{button('review','capacity','納期・部門負荷から改善')}{button('review','value','提供価値・粗利から改善')}</div></article><article className="game-card"><h2>企画の判断履歴</h2>{p.history.length?<ol>{p.history.map((s,i)=><li key={i}>{s}</li>)}</ol>:<p>企画を実行すると、根拠と効果がここに残ります。</p>}</article></>}
 <p className="game-fine">求人の営業企画業務を参考にした架空の学習モデルです。営業企画は関係部門と調整し、計画・提案・実行管理を行います。ゲームでの採用・設計・保守の操作は経営上の簡略表現で、実務を一人で担当する意味ではありません。</p></section>
}
