'use client';
import {useEffect,useState} from 'react';
import {Factory,BriefcaseBusiness,HardHat,Sun,BatteryCharging,MonitorCog,Play,Pause,ArrowRight,RotateCcw,FileText,UserRound,Zap} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import data from '@/data/work-experience.json';
const icons=[Factory,BriefcaseBusiness,HardHat,Sun,BatteryCharging,MonitorCog];
export default function WorkExperience(){
 const [stage,setStage]=useState(0),[beat,setBeat]=useState(0),[playing,setPlaying]=useState(false),[choice,setChoice]=useState<number|null>(null),[place,setPlace]=useState<string|null>(null),[view,setView]=useState('all');
 const s=data.stages[stage],from=data.places.find(p=>p.id===s.from)!,to=data.places.find(p=>p.id===s.to)!;
 const selected=data.places.find(p=>p.id===place),answer=choice===null?null:s.choices[choice];
 const route=`M ${from.x} ${from.y+25} Q ${(from.x+to.x)/2} ${Math.min(from.y,to.y)-25} ${to.x} ${to.y+25}`;
 function go(i:number){setStage(i);setBeat(0);setPlaying(false);setChoice(null);setPlace(null)}
 useEffect(()=>{if(!playing)return;const t=setTimeout(()=>{if(beat<2)setBeat(beat+1);else setPlaying(false)},3500);return ()=>clearTimeout(t)},[playing,beat]);
 return <section className="panel worktour" id="work-tour"><div className="paneltitle"><h2>ESSの現場と仕事を体験する</h2><span className="badge">仮想案件・業務分担は学習用の想定</span></div><p>ある工場の相談から、導入・毎日の運転・改善まで。場所をクリックして見学し、次に何をするか判断します。</p><div className="work-phases" aria-label="仕事体験の場面">{data.stages.map((v,i)=><button key={v.name} aria-current={i===stage?'step':undefined} className={i===stage?'active':''} onClick={()=>go(i)}><small>{i+1}</small>{v.name}</button>)}</div><div className="work-toolbar"><span><b>SCENE {stage+1}</b>　{s.when}</span><Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList><TabsTrigger value="all">現場全体</TabsTrigger><TabsTrigger value="planner">営業企画に注目</TabsTrigger></TabsList></Tabs></div>
 <div className={'work-map '+(playing?'playing':'')}><svg viewBox="0 0 880 470" role="img" aria-label={`${s.from}から${s.to}へ${s.parcel}が移動する仕事の模式図`}><defs><marker id="work-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="none" stroke="currentColor"/></marker></defs><rect x="25" y="20" width="830" height="175" rx="14" fill="#edf3fa"/><rect x="25" y="245" width="830" height="205" rx="14" fill="#eaf4f1"/><text x="40" y="42" className="zone-label">顧客・企画・導入チーム</text><text x="40" y="269" className="zone-label">設備・運用の現場（配置は模式図）</text><path d="M160 110H720M160 350H720M440 110V350M720 110V350M160 110V350" fill="none" stroke="#c4d3e1" strokeDasharray="6 7" strokeWidth="2"/><path d={route} fill="none" stroke={s.kind==='electricity'?'#1b9979':'#286dcc'} strokeWidth="4" markerEnd="url(#work-arrow)"/><g key={`${stage}-${beat}-${playing}`} className="work-token" style={{offsetPath:`path('${route}')`,offsetDistance:playing?undefined:'50%'}}><circle r="18" fill={s.kind==='electricity'?'#147c61':'#1d589e'}/>{s.kind==='people'?<UserRound x="-10" y="-10" width="20" height="20" color="white"/>:s.kind==='electricity'?<Zap x="-10" y="-10" width="20" height="20" color="white"/>:<FileText x="-10" y="-10" width="20" height="20" color="white"/>}</g></svg>{data.places.map((p,i)=>{const Icon=icons[i],active=p.id===s.from||p.id===s.to;return <button key={p.id} className={'work-place '+(active?'active ':'')+(view==='planner'&&p.id==='planning'?'planner-focus ':'')} style={{left:`${p.x/880*100}%`,top:`${p.y/470*100}%`}} onClick={()=>setPlace(p.id)} aria-pressed={place===p.id}><Icon size={27}/><strong>{p.name}</strong><span>{p.role}</span>{active&&<small>{p.id===s.from?'発信・対応する側':'受け取る側'}</small>}</button>})}<div className="work-moving-label">{s.kind==='people'?'人の対応':s.kind==='electricity'?'電気の流れ':'情報の受け渡し'}：{s.parcel}</div></div>
 {selected&&<div className="work-place-info"><strong>{selected.name}</strong><p>{selected.detail}</p><button onClick={()=>setPlace(null)}>閉じる</button></div>}
 <div className="work-narration"><div className="work-player"><button className="primary" onClick={()=>{if(!playing&&beat===2)setBeat(0);setPlaying(!playing)}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'一時停止':'この場面を再生'}</button><button className="secondary" aria-label="場面を最初から" onClick={()=>{setBeat(0);setPlaying(false)}}><RotateCcw size={16}/></button><span>動きの説明 {beat+1} / 3</span><button className="secondary" disabled={beat===2} onClick={()=>{setPlaying(false);setBeat(beat+1)}}>説明を進める</button></div><h3>{s.caption}</h3><p aria-live="polite" className="work-subtitle">{s.beats[beat]}</p><span className="work-numbers">{s.numbers}</span></div>
 <div className="work-roles"><div><span className="eyebrow">この場面を動かす人・仕組み</span><h3>{s.actor}</h3><p>{s.status}</p></div><div className={view==='planner'?'emphasized':''}><span className="eyebrow">営業企画が関わること</span><p>{s.planner}</p></div></div>
 <div className="work-decision"><span className="eyebrow">あなたなら、次にどう考える？</span><h3>{s.question}</h3><div className="work-choices">{s.choices.map((v,i)=><button key={v.text} className={choice===i?'chosen':''} onClick={()=>{setChoice(i);setPlaying(false)}} aria-pressed={choice===i}><b>{i===0?'A':'B'}</b>{v.text}</button>)}</div>{answer&&<div className={'work-feedback '+(answer.good?'good':'rethink')} role="status"><strong>{answer.good?'その判断が次の仕事につながります':'ここを確認してから進めましょう'}</strong><p>{answer.result}</p></div>}</div><div className="work-output"><FileText size={24}/><div><span>この場面で残すもの・次へ渡すもの</span><strong>{s.deliverable}</strong></div></div><div className="work-next"><button className="secondary" disabled={stage===0} onClick={()=>go(stage-1)}>前の場面</button><span>{stage+1} / {data.stages.length}</span><button className="primary" onClick={()=>go(stage===data.stages.length-1?0:stage+1)}>{stage===data.stages.length-1?'最初から見直す':'次の場面へ'}<ArrowRight size={16}/></button></div><details className="sim-assumptions"><summary>実際の仕事との関係・出典</summary><p>GSユアサの公式求人は事業企画・実行、市場や顧客の調査、販売促進、製品企画、社外連携・渉外等を示しています。この体験の工場案件、担当者の動線、工程、会話、数値、成果物は理解のために構成した想定です。会社の実際の組織・承認手順を再現したものではありません。</p><p>監視室と設備は実際には離れていることがあります。担当者の移動は対応先・情報の受け渡しを表し、毎回出張することを意味しません。詳細な機器操作・施工・故障対応は専門担当の領域です。</p><a className="source" href="https://js01.jposting.net/gs-yuasa/u/job.phtml?job_code=791" target="_blank" rel="noreferrer">公式求人：常用（ESS）市場の営業企画</a><br/><a className="source" href="https://ps.gs-yuasa.com/es/products/" target="_blank" rel="noreferrer">公式：蓄電システム・STARELINKの製品紹介</a></details></section>
}
